version: '3.8'

services:
  # Base de datos
  db:
    image: postgres:15-alpine
    container_name: invex_app_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC # Forzamos a la BD a trabajar en UTC
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      # Este script se ejecutará solo la primera vez para crear las tablas
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
